version: '3'
services:
     web:
         build: .
         container_name: main_web_rry235
         ports:
             - 5039:5000
     
     redis:
         image: redis:latest
         ports:
             - 6419:6379
         volumes:
             - ./config/redis.conf:/redis.conf
         command: ["redis-server", "/redis.conf" ]
