---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rry235-hw7-worker-deployment
  labels:
    app: rry235-hw7-worker
    username: rry235
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rry235-hw7-worker
  template:
    metadata:
      labels:
        app: rry235-hw7-worker
        username: rry235
        env: test
    spec:
      containers:
        - name: rry235-hw7-worker
          imagePullPolicy: Always
          image: rileyylagan/coe332-worker:latest
          env:
            - name: "WORKER_IP"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP