---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rry235-hw7-redis-pvc
  labels:
    username: rry235
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi