---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rry235final-prod-wrk-deployment
  labels:
    app: rry235final-prod-wrk
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rry235final-prod-wrk
  template:
    metadata:
      labels:
        app: rry235final-prod-wrk
        env: prod
    spec:
      containers:
        - name: rry235final-prod-wrk
          image: rileyylagan/rry235final-app-wrk:${TAG}
          imagePullPolicy: Always
          env:
          - name: REDIS_IP
            value: 10.102.208.240 
...
